#!/usr/bin/env python3
"""Regenerate src/keysym.rs from X11's keysymdef.h and Python's unicodedata.

    python3 scripts/gen-keysym.py > src/keysym.rs

Needs the x11proto headers (Debian: xorg-dev). The output is layout-agnostic:
adding a keyboard layout never touches it.
"""
import os, re, sys, unicodedata

KEYSYMDEF = "/usr/include/X11/keysymdef.h"
SYMBOLS = "/usr/share/X11/xkb/symbols"

# Dead keysym name -> (character it types on its own, combining mark).
# Spacing forms follow what XKB's own compose rules produce for dead + space.
DEAD = {
    "grave":       ("`", "̀"),
    "acute":       ("´", "́"),
    "circumflex":  ("^", "̂"),
    "tilde":       ("~", "̃"),
    "macron":      ("¯", "̄"),
    "breve":       ("˘", "̆"),
    "abovedot":    ("˙", "̇"),
    "diaeresis":   ("¨", "̈"),
    "abovering":   ("˚", "̊"),
    "doubleacute": ("˝", "̋"),
    "caron":       ("ˇ", "̌"),
    "cedilla":     ("¸", "̧"),
    "ogonek":      ("˛", "̨"),
}

def esc(ch):
    return "'\\u{%x}'" % ord(ch)

def names():
    """Every name to the text it types.

    The U+ comment when keysymdef gives one, otherwise the keysym value
    itself: Latin-1 keysyms are their own codepoint, and 0x01000000+N is
    U+N. Deprecated aliases such as XK_masculine carry no U+ comment but are
    still what older XKB symbol files use, so they have to resolve.
    """
    pat = re.compile(r"^#define XK_(\w+)\s+0x([0-9a-fA-F]+)(?:\s*/\*\s*U\+([0-9A-Fa-f]{4,6}))?")
    out = {}
    for line in open(KEYSYMDEF, encoding="utf-8", errors="replace"):
        m = pat.match(line)
        if not m:
            continue
        if m.group(3):
            out.setdefault(m.group(1), chr(int(m.group(3), 16)))
            continue
        v = int(m.group(2), 16)
        if 0x20 <= v <= 0x7E or 0xA0 <= v <= 0xFF:
            out.setdefault(m.group(1), chr(v))
        elif 0x01000000 <= v <= 0x0110FFFF:
            out.setdefault(m.group(1), chr(v - 0x01000000))
    return out

def compose():
    marks = {mark for _, mark in DEAD.values()}
    out = []
    for cp in range(0x110000):
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = d.split()
        if len(parts) != 2:
            continue
        base, mark = (chr(int(p, 16)) for p in parts)
        if mark in marks:
            out.append((base, mark, chr(cp)))
    return sorted(out)

def referenced():
    """Keysym names some shipped layout can actually produce.

    keysymdef carries ~660 names no xkb symbols file ever mentions, and a
    name we cannot resolve just relays the key, so dropping them costs
    nothing and is still not per-language.
    """
    used, pat = set(), re.compile(r"[A-Za-z0-9_]+")
    for root, _, files in os.walk(SYMBOLS):
        for f in files:
            text = open(os.path.join(root, f), encoding="utf-8", errors="replace").read()
            for group in re.findall(r"\[([^]]*)\]", text):
                used.update(pat.fullmatch(t.strip()).group() for t in group.split(",")
                            if pat.fullmatch(t.strip()))
    return used

def rows(items, width=96):
    """Several per line. The data is generated, it does not need one line each."""
    line, out = "", []
    for it in items:
        if line and len(line) + len(it) + 1 > width:
            out.append("    " + line)
            line = ""
        line += it + ","
    if line:
        out.append("    " + line)
    return "\n".join(out) + "\n"

n, c = names(), compose()
keep = referenced()
n = {k: v for k, v in n.items() if k in keep}
w = sys.stdout.write
w("//! Generated by scripts/gen-keysym.py. Do not edit.\n")
w("//!\n")
w("//! Keysym names as `xkbcomp -xkb` prints them, mapped to the text they\n")
w("//! type. Layout-agnostic: a new keyboard layout needs nothing here.\n\n")

w("/// Sorted by name for binary search.\n")
w("pub const NAMES: &[(&str, char)] = &[\n")
w(rows(['("%s",%s)' % (k, esc(n[k])) for k in sorted(n)]))
w("];\n\n")

w("/// Dead key suffix -> (character it types alone, combining mark).\n")
w("pub const DEAD: &[(&str, char, char)] = &[\n")
for k in sorted(DEAD):
    s, m = DEAD[k]
    w("    (\"%s\", %s, %s),\n" % (k, esc(s), esc(m)))
w("];\n\n")

w("/// (base, combining mark) -> precomposed, sorted for binary search.\n")
w("pub const COMPOSE: &[(char, char, char)] = &[\n")
w(rows(["(%s,%s,%s)" % (esc(b), esc(m), esc(o)) for b, m, o in c]))
w("];\n")

w('''
/// The text a keysym types, or None when it types none. Names X resolves
/// numerically or as `U00E7` are handled arithmetically, the rest by table.
pub fn to_char(sym: &str) -> Option<char> {
    if sym == "NoSymbol" || sym == "VoidSymbol" {
        return None;
    }
    if let Some(hex) = sym.strip_prefix("0x") {
        return from_keysym(u32::from_str_radix(hex, 16).ok()?);
    }
    if let Some(hex) = sym.strip_prefix('U') {
        if hex.len() >= 4 && hex.chars().all(|c| c.is_ascii_hexdigit()) {
            return char::from_u32(u32::from_str_radix(hex, 16).ok()?);
        }
    }
    NAMES
        .binary_search_by_key(&sym, |(n, _)| n)
        .ok()
        .map(|i| NAMES[i].1)
}

/// Latin-1 keysyms are their own codepoint, and anything above 0x01000000 is
/// Unicode with a tag. Everything else needs the table.
fn from_keysym(value: u32) -> Option<char> {
    match value {
        0x20..=0x7e | 0xa0..=0xff => char::from_u32(value),
        0x0100_0000..=0x0110_ffff => char::from_u32(value - 0x0100_0000),
        _ => None,
    }
}

/// For `dead_acute` and friends: the character it types alone, and its
/// combining mark. None for accents we have no mark for, which leaves the key
/// relayed rather than swallowing the press that follows it.
pub fn dead(sym: &str) -> Option<(char, char)> {
    let name = sym.strip_prefix("dead_")?;
    DEAD.binary_search_by_key(&name, |(n, _, _)| n)
        .ok()
        .map(|i| (DEAD[i].1, DEAD[i].2))
}

/// The precomposed character for a base and a combining mark, when one exists.
pub fn compose(base: char, mark: char) -> Option<char> {
    COMPOSE
        .binary_search_by_key(&(base, mark), |(b, m, _)| (*b, *m))
        .ok()
        .map(|i| COMPOSE[i].2)
}
''')
